# Copyright 2013 Donald Stufft and individual contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import absolute_import, division, print_function

import pytest

import nacl.encoding
import nacl.exceptions
import nacl.auth


class TestAuthGenerate:

    def test_generate(self):
        a = nacl.auth.generate(b"foo", b"1" * nacl.auth.KEY_SIZE)
        assert len(a) == nacl.auth.AUTH_SIZE

    @pytest.mark.parametrize("encoder", [
        nacl.encoding.HexEncoder,
        nacl.encoding.RawEncoder,
    ])
    def test_encoding(self, encoder):
        rawmsg = b"foo"
        rawkey = b"1" * nacl.auth.KEY_SIZE

        encmsg = encoder.encode(rawmsg)
        enckey = encoder.encode(rawkey)

        a1 = nacl.auth.generate(rawmsg, rawkey)
        a2 = nacl.auth.generate(encmsg, enckey, encoder)

        assert a1 == encoder.decode(a2)

    def test_wrong_length(self):
        with pytest.raises(ValueError):
            nacl.auth.generate(b"foo", b"1" * 31)


class TestAuthVerify:

    def test_verify(self):
        msg = b"foo"
        key = b"1" * nacl.auth.KEY_SIZE

        a = nacl.auth.generate(msg, key)
        assert len(a) == nacl.auth.AUTH_SIZE

    @pytest.mark.parametrize("encoder", [
        nacl.encoding.HexEncoder,
        nacl.encoding.RawEncoder,
    ])
    def test_encoding(self, encoder):
        rawmsg = b"foo"
        rawkey = b"1" * nacl.auth.KEY_SIZE

        encmsg = encoder.encode(rawmsg)
        enckey = encoder.encode(rawkey)

        a = nacl.auth.generate(encmsg, enckey, encoder)
        assert nacl.auth.verify(a, encmsg, enckey, encoder)

    @pytest.mark.parametrize(("msg", "key", "a"), [
        (
            b'12e88ecb241226f24d298685de7ad2cc93ed745f',
            b'09f61ec34505cd0f4c9dddaa15cbae2e' * 2,
            b'e6660c2b1096fa06cc0613648d814241'
            b'baf40b0ce9535c67ec917de147c178b5',
        )
    ])
    def test_positive_samples(self, msg, key, a):
        assert nacl.auth.verify(a, msg, key, nacl.encoding.HexEncoder)

    @pytest.mark.parametrize(("msg", "key", "a"), [
        (
            # corrupt msg
            b'A2e88ecb241226f24d298685de7ad2cc93ed745f',
            b'09f61ec34505cd0f4c9dddaa15cbae2e' * 2,
            b'e6660c2b1096fa06cc0613648d814241'
            b'baf40b0ce9535c67ec917de147c178b5',
        ),
        (
            # a was generated by tweet-nacl
            # corrupt key
            b'12e88ecb241226f24d298685de7ad2cc93ed745f',
            b'A9f61ec34505cd0f4c9dddaa15cbae2e' * 2,
            b'e6660c2b1096fa06cc0613648d814241'
            b'baf40b0ce9535c67ec917de147c178b5',
        ),
        (
            # a was generated by tweet-nacl
            # corrupt authenticator
            b'12e88ecb241226f24d298685de7ad2cc93ed745f',
            b'09f61ec34505cd0f4c9dddaa15cbae2e' * 2,
            b'A6660c2b1096fa06cc0613648d814241'
            b'baf40b0ce9535c67ec917de147c178b5',
        )
    ])
    def test_negative_samples(self, msg, key, a):
        with pytest.raises(nacl.exceptions.BadSignatureError):
            nacl.auth.verify(a, msg, key, nacl.encoding.HexEncoder)

    def test_wrong_auth_length(self):
        with pytest.raises(ValueError):
            nacl.auth.verify(b"1" * (nacl.auth.AUTH_SIZE + 1),
                             b"foo",
                             b"1" * nacl.auth.KEY_SIZE)

    def test_wrong_key_length(self):
        with pytest.raises(ValueError):
            nacl.auth.verify(b"1" * nacl.auth.AUTH_SIZE,
                             b"foo",
                             b"1" * (nacl.auth.KEY_SIZE - 1))
